#!/bin/bash

# Simple Password Generator
# Author: James Weiner
# Date: 6/8/2024
# Resources: Youtube: HackerSploit
# This script generates a certain number of random passwords that are a specified length

echo "Welcome to the Password Generator"

sleep 1 # This delays the next prompt by 1 second

echo "Please enter the length of the password: " # Prompt for the password length
read PASS_LENGTH # Reads the response to the prompt and stores it in a variable

# Validate that PASS_LENGTH is a positive number
if ! [[ "$PASS_LENGTH" =~ ^[1-9][0-9]*$ ]]; then
	echo "Invalid password length. Please enter a positive number."
	exit 1
fi

echo "Please enter the number of passwords you want generated: "
read NUMBER_OF_PASSWORDS # Reads the response to the prompt and stores it in a variable

# Validate that NUM_PASS is a positive number
if ! [[ "$NUMBER_OF_PASSWORDS" =~ ^[1-9][0-9]*$ ]]; then
    echo "Invalid number of passwords. Please enter a positive number."
    exit 1
fi

#Generate the random passwords based on the number of passwords desired
for p in $(seq $NUMBER_OF_PASSWORDS); #the number of sequences relies on the number of passwords
do
    openssl rand -base64 48 | cut -c1-$PASS_LENGTH # Generate the password
done

